### PR TITLE
Fixes for issues 16 & 18

### PR DESCRIPTION
**Pull request by montegoulding**
[Review on Reviewable](https://reviewable.io/reviews/peter-b/atom-language-livecode/20)

### CODE REVIEW

**Comment by peter-b** [comment]
@montegoulding Thank you so much for looking into this so promptly!

**Comment by montegoulding** [comment]
This latest commit adds support for:

```
if condition then something1 else something2
```

It also adds support for the following with a quirk on the else. Atom seems to decrease the indent when it hits a match but doesn't increase it again when it no longer matches. This means when you are typing else it will step back at the end of the word and if you keep typing it stays at the wrong indent instead of popping back as it should. Using the menu to reset the indents does fix it though. I guess this is reportable on Atom...

```
if condition
then something1
else something2
```

**Comment by peter-b** [comment]
@montegoulding I'm really sorry, but all the contents of your last comment should be in the commit message.  Can you `git commit --amend` it, please?  It's so important to have commit messages that accurately reflect the contents of the diff.

**Comment by montegoulding** [comment]
OK, force pushing to a branch that mid PR worked better than I expected ;-)

**Comment by peter-b** [comment]
@montegoulding Thanks for that.  On Monday I'll try and reorganise the docs a bit to make it a little clearer, and then do a 0.6.1.

**Pull request merged**
