### PR TITLE
Refactor to merge LiveCode Script and iRev

### PR DESCRIPTION
**Pull request by montegoulding**
The linter now detects server scripts by looking for the opening tag
in the script. This change enables us to use the same set of generated
autocomplete snippets without duplicating them. It also makes
maintenance easier by reducing grammar duplication.

[Review on Reviewable](https://reviewable.io/reviews/peter-b/atom-language-livecode/13)

### CODE REVIEW

**Comment by montegoulding** [comment]
Er... hold the phone on this as it breaks other grammars. I just checked php. I'll see what I can come up with but I have a lot on right now so perhaps target this at 0.7 release so it doesn't hold things up.

**Comment by montegoulding** [comment]
Hmm... whitespace diffs. Atom strips all the trailing whitespace from files you touch sorry. I'll investigate the merge conflict

**Comment by montegoulding** [comment]
Sorry, it was a whitespace issue on a spot where I've been testing the linter. Should merge cleanly now.

**Comment by peter-b** [comment]
This looks good, thanks.

**Pull request merged**
